### ISSUE TITLE
Res. 1920x1200 timer out of frame

### ISSUE THREAD

**Issue by gamebeaker** [B2ORG/T6-B2OP-PATCH#3]
If the resolution is 1920x1200 (16:10) instead of 1920x1080 (16:9) the timers are a little bit out of frame.
![grafik](https://github.com/Zi0MIX/T6-B2OP-PATCH/assets/9269847/d0cd2069-a8dd-43eb-af93-0273b5c51960)

**Comment by Zi0MIX** [comment]
Fixed for 4:3, 5:4 and 16:10, shouldn't be cut off anymore
