### ISSUE TITLE
MOTD - lb command issues

### ISSUE THREAD

**Issue by VatrixX** [B2ORG/T6-B2OP-PATCH#5]
### Me and my friend are both experiencing issues with the box locations using the patch. 

When lb command is used, 3/4 of the time, the box will just disappear from the map. The orange light will be glowing towards the good location... but the box won't be there. Even if we try to bring it back to that specific location (warden, even cafe as well), it won't work.
We will usually wait up to 3 full rounds before moving to the wanted location... so clearly enough time for the box to move.

### What we've tried so far : 
- Letting my friend using the commands, via chat or "/". > **Didn't work**
- Pairing the command with "fb". > **Didn't work**
- Restarting **multiple** times, even the Pltonium's client. > **Didn't work**
- As I am usually hosting the games, we've also tried with my friend having the patch downloaded as well. > **Same results**

**To note** : I've also experienced that kind of issues in Solo, but it's way **less** recurrent for some reasons!

**Comment by Zi0MIX** [comment]
Fixed (hopefully) for the next release, feel free to open another if problem persist after using it with upcoming release
