### ISSUE TITLE
error on loading map

### ISSUE THREAD

**Issue by labukomods** [B2ORG/T6-B2OP-PATCH#7]
![Screenshot 2024-10-02 182639](https://github.com/user-attachments/assets/a3760fd5-2bea-49b0-bc03-9445eb93d850)

i am using redacted_LAN
it errors on both solo and custom game
it errors on any map

**Comment by Zi0MIX** [comment]
It appears you're downloading raw code instead of the release version, please read installation instructions
https://github.com/B2ORG/T6-B2OP-PATCH?tab=readme-ov-file#installation
